sudo: required
services:
  - docker

before_install:
  - docker build -t keyhouck/docker-react2 -f Dockerfile.dev .

script:
  - docker run keyhouck/docker-react2 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-401554345623"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
